-- Tables as they exist in the original sfbench DB (GORM AutoMigrate shape), minus empty side tables.
-- datasources additionally carries sensitive_state from the datasource-is-sensitive-flag branch.
-- Indexes live in indexes.sql and are built after the load.

CREATE TABLE sensitive_fields (
    updated_at timestamp with time zone,
    created_at timestamp with time zone,
    scan_id integer,
    pii_type_matched_values jsonb,
    deleted_at timestamp with time zone,
    table_name text,
    datasource_type text,
    database_name text,
    skip_reason text,
    status text DEFAULT 'confirmed'::text NOT NULL,
    field_name text,
    pii_evidence_file_url text,
    datasource_name text,
    doc_type text,
    datasource_identifier text,
    skip_details text,
    semantic_types text[],
    sfd_types text[],
    sfd_confidence bigint,
    row_count bigint,
    sensitivity bigint,
    first_found bigint,
    confidence bigint,
    risk bigint,
    doc_type_confidence bigint,
    table_o_id bigint,
    id text NOT NULL,
    dirty boolean DEFAULT false NOT NULL,
    is_archived boolean DEFAULT false NOT NULL,
    might_be_encrypted boolean DEFAULT false NOT NULL
);

CREATE TABLE sensitivefield_tags (
    sensitive_field_id text NOT NULL,
    tag_id bigint NOT NULL
);

CREATE TABLE tags (
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    id bigserial PRIMARY KEY,
    name text CONSTRAINT uni_tags_name UNIQUE,
    pre_defined boolean
);

INSERT INTO tags (id, name, pre_defined, created_at, updated_at) VALUES
    (1, 'Identity', true, now(), now()),
    (2, 'Financial', true, now(), now()),
    (3, 'Health', true, now(), now()),
    (4, 'Contact', true, now(), now()),
    (5, 'Technical', true, now(), now());
SELECT setval('tags_id_seq', 5);

CREATE TABLE datasources (
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    first_found_at timestamp with time zone,
    last_scanned_at timestamp with time zone,
    updated_threat_level_at timestamp with time zone,
    last_audit_log_monitoring_enabled_at timestamp with time zone,
    last_audit_log_monitoring_disabled_at timestamp with time zone,
    last_schema_scan_start_time timestamp with time zone,
    last_schema_scan_end_time timestamp with time zone,
    sensitivity_count jsonb,
    metadata jsonb,
    cloud_tags jsonb,
    last_scan_request_id bigint,
    last_db_access_control_scan_end_time timestamp with time zone,
    region text,
    country text,
    controller_uuid text,
    password text,
    proxy_port text,
    provider text,
    port text NOT NULL,
    account text,
    scan_error_message text,
    ip_address text,
    db_user text,
    class text,
    encrypted_status text,
    publicly_accessible text,
    versioning_allowed text,
    host text NOT NULL,
    name text,
    arn text,
    risk_score_evidence text DEFAULT '[]'::text,
    is_audit_log_monitoring_enabled_status text DEFAULT 'disabled'::text,
    database_name text,
    product_version text,
    engine_version text,
    semantic_types text[],
    size bigint,
    inventory_status bigint,
    creation_source bigint DEFAULT 0 NOT NULL,
    deleted_at bigint,
    type bigint,
    expected_status bigint,
    scan_status bigint,
    risk_score bigint,
    total_table_count bigint,
    scanned_table_count bigint,
    last_scan_start_time bigint,
    last_scan_end_time bigint,
    last_seen_time bigint,
    last_query_at bigint DEFAULT 0,
    threat_level bigint,
    status bigint,
    health_status bigint,
    avg_successful_scan_time bigint,
    errored_scan_count bigint,
    completed_scan_count bigint,
    scan_time_interval bigint DEFAULT 2592000,
    compliance_score bigint DEFAULT 100,
    service_type bigint,
    scan_query_start_time bigint,
    scan_query_end_time bigint,
    last_scan_update_time bigint,
    scan_id bigint,
    ds_scan_id bigint,
    audit_log_monitoring_type bigint,
    id text NOT NULL,
    is_discovery_audited boolean DEFAULT false,
    is_versioning_allowed boolean,
    is_publicly_accessible boolean,
    is_encrypted_status boolean,
    is_controller_connecting boolean,
    is_manually_added boolean,
    is_onboarded boolean DEFAULT false,
    credential_status boolean,
    is_shared_externally boolean DEFAULT false,
    is_associated_instance boolean,
    is_archived boolean DEFAULT false,
    proxy_flag boolean,
    is_audit_log_enabled boolean,
    is_audit_log_monitoring_enabled boolean,
    sensitive_state text,
    sensitive_state_updated_at timestamp with time zone
);
